spring:
  application:
    name: sio
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_chatbot
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      # Redis Keyspace Notifications 활성화 (TTL 만료 이벤트)
      config:
        notify-keyspace-events: Ex

api:
  key: ${GEMINI_API_KEY:your-api-key-here}
  base-url: https://generativelanguage.googleapis.com/v1beta
  model: gemini-2.0-flash

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure}
  expiration: 86400000 # 24??